### ISSUE TITLE
How can I detect buildings from my own pictures?

### ISSUE THREAD

**Issue by QJvic** [neptune-ai/open-solution-mapping-challenge#195]
I only find this command:`python main.py -- evaluate_predict --pipeline_name unet_tta --chunk_size 1000`.It seems to evaluate model and predict on test data.Can you give me some tips on how to use the model to detect buildings from my own pictures?Thank you very much.

**Comment by jakubczakon** [comment]
Hi @QJvic 

Check the answer on [project discussions board](https://app.neptune.ml/neptune-ml/Mapping-Challenge/discussion)

**Comment by bogdanov1ch** [comment]
> 
> 
> Hi @QJvic
> 
> Check the answer on [project discussions board](https://app.neptune.ml/neptune-ml/Mapping-Challenge/discussion)

@jakubczakon, there is no discussions board if I follow the link, may be I can read about it somewhere else?
